Repository fnplus/Python-scripts-collection, pull requests merged in 2019-11, with the labels that each got.

#32 Improvement of Date iterator
  DateIterator/Date_iterator.py
Labels: enhancement, hacktoberfest

#33 Improvement of the file locator
  FileLocator/code.py
Labels: enhancement, hacktoberfest

#34 Improvement of the youtube downloader
  YouTubeDownloader/youTubeDownload.py
Labels: documentation, enhancement, hacktoberfest

#35 Added automatic email sending script
  GenerateSyntheticCustomerDatabase/GenerateSyntheticCustomerDatabase.py
  README.md
  SendEmail/SendEmail.py
Labels: enhancement, hacktoberfest

#37 Youtube MP4 Download
  YouTubeDownloader/YoutubeMP4Playlist.py
Labels: enhancement, hacktoberfest

#38 Extensions changer
  Rename_files_of_a_folder/ChangeExtensions.py
Labels: enhancement, hacktoberfest

#39 Update link to Instagram Liker in README.md
  README.md
Labels: documentation
